//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloristeriaMillan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto_proveedor
    {
        public decimal idProvCon { get; set; }
        public decimal idProv { get; set; }
        public string nombreCon { get; set; }
        public Nullable<decimal> telefonoCon { get; set; }
        public string emailCon { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
    }
}
