//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloristeriaMillan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionesCliente
    {
        public decimal idDir { get; set; }
        public decimal idUsu { get; set; }
        public string nombreDir { get; set; }
        public string direccionDir { get; set; }
        public string calleDir { get; set; }
        public string coloniaDir { get; set; }
        public string municipioDir { get; set; }
        public Nullable<decimal> codigoPostalCli { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
