//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloristeriaMillan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Factura_desglosada = new HashSet<Factura_desglosada>();
        }
    
        public decimal idFac { get; set; }
        public decimal idUsu { get; set; }
        public Nullable<System.DateTime> fechaEntregaFac { get; set; }
        public Nullable<decimal> totalFac { get; set; }
        public string direccionEntregaFac { get; set; }
        public string metodoPagoFac { get; set; }
        public Nullable<decimal> estatusFac { get; set; }
        public string dedicatoriaFac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura_desglosada> Factura_desglosada { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
