//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloristeriaMillan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_desglosada
    {
        public decimal idFacDes { get; set; }
        public decimal idFac { get; set; }
        public decimal idPro { get; set; }
        public Nullable<decimal> cantidadProductoFacDes { get; set; }
        public Nullable<decimal> totalParcialFacDes { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
