//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloristeriaMillan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Carrito = new HashSet<Carrito>();
            this.DireccionesCliente = new HashSet<DireccionesCliente>();
            this.Factura = new HashSet<Factura>();
            this.Favoritos = new HashSet<Favoritos>();
        }
    
        public decimal idUsu { get; set; }
        public string nombreCli { get; set; }
        public string emailCli { get; set; }
        public string passwordCli { get; set; }
        public Nullable<decimal> telefonoCli { get; set; }
        public decimal idRol { get; set; }
        public string calleCli { get; set; }
        public string coloniaCli { get; set; }
        public string municipioCli { get; set; }
        public Nullable<decimal> codigoPostalCli { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrito> Carrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DireccionesCliente> DireccionesCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favoritos> Favoritos { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
